### PR TITLE
added DotNet.ReproducibleBuilds 

### LINKED ISSUE #8: Enable deterministic build
Add [DotNet.ReproducibleBuilds](https://github.com/dotnet/reproducible-builds#dotnetreproduciblebuilds-nuget-package) to make [deterministic builds](https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/):

> Deterministic builds ensure that the same binary is produced regardless of the machine building it, including paths to sources stored in the symbols.

With this package all settings are enabled, PDBs and sourcelink infos are embedded into the DLL. With this you can step into source code without cloning the repo and using a self compiled DLL.

### PR DESCRIPTION
**Pull request by MagicAndre1981**
added DotNet.ReproducibleBuilds to fix #8

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
Very good stuff, thank you for your contribution! Would you like your name to be listed under the contributors?

**Comment by MarkCiliaVincenti** [comment]
> Very good stuff, thank you for your contribution! Would you like your name to be listed under the contributors?

Over here that is; ideally I'd have your real name:

https://github.com/MarkCiliaVincenti/AsyncKeyedLock/blob/master/CONTRIBUTORS.md

**Comment by MagicAndre1981** [comment]
just add my username from github

**Comment by MarkCiliaVincenti** [comment]
> just add my username from github

Mia San Mia

Done

**Comment by MarkCiliaVincenti** [comment]
Included in release 6.1.1 :)

**Pull request merged**
